name: Deploy

on:
  push:
    branches:
      - master

env:
  APP_NAME: evento-tracker
  HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}

jobs:
  deploy:
    name: Deploy to Heroku
    if: github.repository == 'damian-rzeszot/eventotracker-server'
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Login to Heroku Container
      run: heroku container:login
    - name: Build and push
      run: heroku container:push -a $APP_NAME web
    - name: Release
      run: heroku container:release -a $APP_NAME web
